### ISSUE TITLE
Sightly Repl not working with AEM6.2

### ISSUE THREAD

**Issue by farah2307** [Adobe-Marketing-Cloud/aem-sightly-repl#15]
I am trying  to run Sightly REPL with AEM 6.2 but it gives me an error in including REPL component.

**Comment by thisisui** [comment]
I also run this on AEM 6.2 and cannot make it work. I see the page but there is no input where I can put my content. No error in console and no errors during package installation.

**Comment by vladbailescu** [comment]
The issue was fixed by @gabrielwalt  in https://github.com/Adobe-Marketing-Cloud/aem-sightly-repl/commit/b93f58941e7680b77167ad3fcc3d76329a163649 but it was not released yet. You can get around it by installing the REPL using Maven: https://github.com/Adobe-Marketing-Cloud/aem-sightly-repl#maven-method

**Comment by raducotescu** [comment]
I've verified REPL on a vanilla AEM 6.2 and everything works correctly now.
