### ISSUE TITLE
Auto Refresh Error

### ISSUE THREAD

**Issue by AxelHo** [Adobe-Marketing-Cloud/aem-sightly-repl#9]
during editing the html template i got the following errors in my console.
Brower Chrome latest Win7
GET http://localhost:4502/libs/granite/csrf/token.json 404 (Not Found)
PUT http://localhost:4502/apps/repl/components/repl/template.html 405 (Method Not Allowed)

**Comment by raducotescu** [comment]
@AxelHo, what version of the REPL tool did you use? On what AEM release did you install REPL?

**Comment by AxelHo** [comment]
aem-6.0.0-SP2-hotfix-6316.jar
Update to  REPL latest with the "click method" described in the readme

**Comment by toniedzwiedz** [comment]
Facing the exact same problem. 404 when requesting the token, 405 when trying to issue the PUT request.

- Adobe Experience Manager, Version 6.0.0.SP1
- com.adobe.granite.sightly.repl-1.0.2.zip (the package linked in the README.md)

_Chrome 44.0.2403.155 m_ on  _Windows 8.1 Enterprise_, same thing happening in _Firefox 40.0.2_ so I strongly doubt it's due to browser issues.
